---
title: "Profesores"
description: |
 \¿Quiénes somos? 
site: distill::distill_website
---

**JUAN PABLO RUIZ NICOLINI**

También conocido como el _TuQmano._ Soy politólogo$^2$ por la Universidad Torcuato Di Tella. Trabajo con datos y visualizaciones. Me gustan las elecciones. *Cientista de Datos* en progreso (*DS*).

Como politólogo [mis temas de investigación](https://www.researchgate.net/profile/Juan-Ruiz-Nicolini) se concentraron en estudios electorales, partidos y reforma política. En particular, he trabajado en la evaluación del impacto político del cambio en la tecnología con la que se emiten los votos.



Como *DS* vengo trabajando en el desarrollo de paquetes de `r icons::fontawesome("r-project")` para [facilitar herramientas y el acceso a datos políticos de Argentina](https://github.com/politicaargentina/).

[`r icons::fontawesome("globe")`](https://www.tuqmano.com/) [tuqmano.ar](https://www.tuqmano.com/) | [`r icons::fontawesome("twitter")`](https://twitter.com/TuQmano) [TuQmano](https://twitter.com/TuQmano) | [`r icons::fontawesome("github")`](https://github.com/tuqmano) [/tuqmano](https://github.com/tuqmano)

------------------------------------------------------------------------

**PABLO TISCORNIA**


Sociólogo (UBA), especializado en metodología, producción y procesamiento de datos estadísticos, principalmente en el ámbito público. Últimamente me encuentro enfocado en la mejora de procesos de trabajo vinculados al tratamiento de datos.

He participado en la organización y difusión de la comunidad de [R en Buenos Aires](https://renbaires.github.io/) y en el desarrollo del [paquetes eph](https://holatam.github.io/eph/), cuyo principal objetivo es facilitar herramientas y el acceso a datos de la Encuesta Permanente de Hogares - INDEC, mediante el lenguaje de programación `R`.

[`r icons::fontawesome("globe")`](https://rpubs.com/pablotisco) [Rpubs-pablotis](https://rpubs.com/pablotisco) | [`r icons::fontawesome("twitter")`](https://twitter.com/pabblo_h) [pabblo_h](https://twitter.com/pabblo_h) | [`r icons::fontawesome("github")`](https://github.com/pablotis) [/pablotis](https://github.com/pablotis)