---
title: "Instrumentos de An&aacute;lisis Urbanos II"
description: "Profesores: Juan Pablo Ruiz Nicolini y Pablo Tiscornia"

site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

```

### **Maestría en Economía Urbana \| Universidad Torcuato Di Tella**

**8 de junio - 17 de agosto de 2021 \| 19.15hs \| VIRTUAL**

#### **Descripción del curso:**

*Instrumentos de Análisis Urbano II* está pensado como un curso aplicado de Ciencia de Datos a temas relacionados con las ciudades. Para ello nos valdremos de un conjunto de herramientas computaciones que en conjunto tienen como objetivo la elaboración de un proyecto de Ciencia de Datos para el análisis urbano: desde la obtención de los datos (de diversas fuentes y formatos); su curaduría, limpieza, procesamiento, análisis y comunicación de los mismos.

Desde el inicio, además, presentaremos una alternativa para la organización del proyecto para potenciar la reproducibilidad de las investigaciones y sacar provecho del control de versiones y el trabajo colaborativo.

## Organización del curso

El curso se divide en tres grandes módulos, cada uno de los cuales se concentra en varias sesiones.

En el primero de ellos, a lo largo de las primeras dos clases, presentaremos el programa, evaluaremos el conocimiento previo de los participantes y avanzaremos con la instalación, puesta a punto y presentación de las herramientas que proponemos utilizar a lo largo de la materia.

El segundo Módulo, que abarca desde la sesión 3 hasta la 6 inclusive, está pensado para introducir herramientas y técnicas para el acceso, limpieza y transformación de datos.

Por último, en el tercer Módulo nos proponemos avanzar en una introducción práctica a diversas técnicas para la visualización de los datos en general y geográficos en particular.

## Práctica y Evaluación

Este curso está pensado para avanzar a través de la práctica de los contenidos. Por lo que se espera de los alumnos una participación activa, con entregas de pequeños ejercicios cotidianamente. Esta participación será parte de la evaluación final ($40\%$). 

El otro $60\%$ es la puntuación máxima del informe que se requerirá como evaluación final. El mismo consistirá en el desarrollo de un proyecto de Ciencia de Datos sobre ciudades que incorpore las distintas herramientas expuestas a lo largo del curso. 


---

# MÓDULOS

## Módulo 1

### Sesión 1: Presentación

-   Configuración de tecnologías y puesta en marcha

### Sesión 2: Introducción

**`R` + RStudio**

-   Organización del flujo de trabajo (.`Rproj`, y `git`)

```{=html}
<!-- -->
```
-   `R base` y el suite *Tidyverse*

-   Reproducibilidad y Comunicación (`.R` y `Rmd`)

    ------------------------------------------------------------------------

## Módulo 2

### Sesión 3: Domar los datos I

**Los principales paquetes y sus verbos para:**

-   leer datos (`readr`, `heaven`, `readxl`, `googlesheets4`, etc)

-   limpiar datos (`tidyr`, `janitor`, `tibble`)

-   transformar datos (`dplyr`)

**Herramientas auxiliares para mejorar el flujo del código:**

-   la pipa de `magrittr` (`%>%`) para encadenar y `glue` para facilitar la concatenación. 

### Sesión 4: Domar los datos II

-   \+`dplyr`

**Ampliando la caja de herramientas:**

-   `lubridate` para trabajar el tiempo

-   `forcats` para datos categóricos (factors)

-   `stringr` para datos de texto

### Sesión 5: Domar los datos III

**Trabajar con *geo* data:**

-   `sf`

-   `rmapshaper`

-   `geoAr`

### Sesión 6: Programación (intro)

**No repetirse uno mismo**

-   Escribir funciones

-   Programación funcional (Introducción a `purrr` )


### Sesión 7: Tópicos I

Obtener datos de la web:

-   ejemplos aplicados con APIs y *web scraping* con `rvest`

------------------------------------------------------------------------

## Módulo 3

### Sesión 8: Data Viz I

**La *Gramática de los Gráficos***

-   Introducción a `ggplot2`

### Sesión 9: Data Viz II

**Las muchas capas de `ggplot2`**

-   `geom_sf()`: para mapas estáticos

Extensiones: `mapsf`,`patchwork`, `cowplot` , entre otros.

### Sesión 10: Data Viz III

**Distintas formas de representar información geográfica:**

-   `leaflet`: para mapas interactivos

-   `geofacet`: para grillas como si fueran mapas

-   `tilemaps`: _cuando el área no importa_

