---
title: "Instrumentos de An&aacute;lisis Urbanos II"
subtitle: "Maestría en Economía Urbana"
author: ""
institute: "Universidad Torcuato Di Tella"
date: "18/07/2022"
output:
  xaringan::moon_reader:
    css: ["footer-header.css", "styles.css"]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      highlightSpans: true
      countIncrementalSlides: false
---

layout: true
  
<div class="my-footer"><span>Instrumentos de Análisis Urbanos II - <a href="https://tuqmano.github.io/geo_utdt/">https://tuqmano.github.io/geo_utdt/</a></span></div> 


```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(collapse = TRUE,
                      fig.retina = 3,
                      out.width = 300, ### control plot size
                      cache = TRUE,
                      warning = FALSE,
                      message = FALSE)


```


```{r xaringan, include=FALSE}
xaringanExtra::use_xaringan_extra(c("tile_view", "animate_css", "tachyons", "extra_styles", "scribble", "editable", "broadcast", "webcam"))


```

```{r extrasXaringan, echo=FALSE}
xaringanExtra::use_extra_styles(
  hover_code_line = TRUE,         #<<
  mute_unhighlighted_code = TRUE  #<<
)

xaringanExtra::use_progress_bar(color = "#fdbd15", location = "top")
```


```{r echo=FALSE}
library(tidyverse)
library(eph)
```


---
# FUNCIONES

## HOJA DE RUTA

- ¿Para qué sirven las funciones?

- Aprender a crear una función propia. 

- "Si se repite más de tres veces, merece ser una función"


---
