---
title: "Instrumentos de Análisis Urbano II"
author: "Juan Pablo Ruiz Nicolini"
date: ""
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### **Maestría en Economía Urbana \| Universidad Torcuato Di Tella**

**21 de junio - 30 de agosto de 2022 \| 19.15hs \| VIRTUAL**

#### **Descripción del curso:**
*Instrumentos de Análisis Urbano II* está pensado como un curso aplicado de Ciencia de Datos para ciudades. Para ello nos valdremos de herramientas computacionales que, en conjunto, tienen como objetivo la elaboración de un proyecto de análisis urbano desde la obtención de los datos (de diversas fuentes y formatos); su curaduría, limpieza, procesamiento, análisis, hasta la comunicación de los mismos.

Desde el inicio, además, propondremos alternativas para la organización del proyecto que apuntan a potenciar la reproducibilidad de las investigaciones y sacar provecho del control de versiones y el trabajo colaborativo.

## Organización del curso

El curso se divide en dos grandes módulos:

1.	Introducción a las principales herramientas de R para el procesamiento de datos.

2.	Introducción a las principales herramientas de R para el procesamiento de datos espaciales y la visualización de la información.

Las clases se estructuran con una presentación del contenido de forma oral seguida de prácticas en clase sobre lo expuesto. El objetivo es que los y las alumnas puedan practicar y disponer de la clase como ámbito de consulta.
 

## Práctica y Evaluación

Este curso está pensado para avanzar a través de la práctica de los contenidos. Por ello se espera de los alumnos una participación activa, con entregas de pequeños ejercicios periódicamente. Esta participación será parte de la evaluación final ($40\%$) que requerirá además la entrega de un informe original sobre un tema urbano que aplique el conjunto de herramientas expuestas a lo largo del curso. La puntuación máxima del informe será el $60\%$ de la nota final. 

Se propone un trabajo final integrador. Se espera en el mismo que se plasme el planteo de un problema plausible de ser respondido con datos y el desarrollo de los procedimientos programáticos en R para la resolución del mismo.

El trabajo debe incluir los contenidos dictados a lo largo de los dos módulos (Planteo de un problema, importación y limpieza de la base de datos, generación de indicadores no espaciales y espaciales y presentación de los resultados. Se ofrece elegir un tema propio o relativo a la base de trabajo que se dará en clase. 

El formato de entrega esperado es un proyecto de trabajo en RStudio vinculado a un repositorio en Github.

---

## Módulo 1

### Sesión 1: Presentación

-   Configuración de herramientas y puesta en marcha

### Sesión 2: Introducción

- Intro a **`R`** y  **RStudio** + Paquetes

-   Organización del flujo de trabajo (.`Rproj`, y `git`)

- Scripts vs _RMarkdown_


### Sesión 3: Domar los datos I

**Los principales paquetes y sus verbos para:**

-   leer datos (`readr`, `heaven`, `readxl`, `googlesheets4`, etc)

-   limpiar datos (`tidyr`, `janitor`, `tibble`)

-   transformar datos (`dplyr`)

**Herramientas auxiliares para mejorar el flujo del código:**

-   la pipa de `magrittr` (`%>%`) para encadenar y `glue` para facilitar la concatenación. 


### Sesión 4: Domar los datos II

-   \+`dplyr`

**Ampliando la caja de herramientas:**

-   `forcats` para datos categóricos (factors)

-   `stringr` para datos de texto

### Sesión 5: R Intermedio


- Funciones

- Iteraciones / _loops_



## Módulo 2: _Domar los datos_(espaciales) y Representación Visual de la Información


### Sesión 6  **Trabajar con *geo* data:**

- Flujo de trabajo con datos espaciales

- Procesamiento de datos con `sf`

- El paquete `geoAr`


### Sesión 7: Data Viz I

- Introducción a la visualización de datos

- **La *Gramática de los Gráficos***

- El paquete `ggplot2`

### Sesión 8: Data Viz II

- Las muchas capas de `ggplot2`

- Facet con `geoAr` para grillas como si fueran mapas

- Composición de gráficos con `patchwork`, `cowplot` , entre otros.

### Sesión 9: GEO Data Viz I

-   `geom_sf()` para mapas estáticos

-   Una alternativa para `mapsf`

### Sesión 10: GEO Data Viz II

-   `leaflet` para mapas interactivos


# BIBLIOGRAFÍA

> `(Los títulos acá listados funcionan como hipervínculo para acceder al material)`

### PRINCIPAL

**Fundamentos**: [*An Intro to R*](https://colinfay.me/intro-to-r/statistical-models-in-r.html), Collin Fay.

**Programación**: [*R para Ciencia de Datos*](https://es.r4ds.hadley.nz/) (Traducción de [*R for Data Science*](https://r4ds.had.co.nz/)*)*, Garrett Grolemund, Hadley Wickham.

**Visualización**: [*ggplot2: Elegant Graphics for Data Analysis*](https://ggplot2-book.org/), Hadley Wickham.

**Geocomputación**: [*Geocomputation with R*](https://geocompr.robinlovelace.net/); Robin Lovelace, Jakub Nowosad & Jannes Muenchow.

------------------------------------------------------------------------

### CONSULTA

#### GENERAL

-   [*AnalizaR Datos Políticos*](https://arcruz0.github.io/libroadp/), Francisco Urdinez y Andrés Cruz Labrín (Editores).

-   [*Ciencia de Datos para Gente Sociable*](https://bitsandbricks.github.io/ciencia_de_datos_gente_sociable/), Antonio Vazquez Brust.

-   [*Ciencia de datos para curiosos*](https://bookdown.org/martinmontaneb/CienciaDeDatosParaCuriosos/), Martín Montané.

#### DATA VIZ

-   [*Data Visualizaction: A Practival Introduction*](https://socviz.co/index.html#preface), Kieran Healey.

-   [*Fundamentals of Data Visualization*](https://clauswilke.com/dataviz/), Claus Wilke.

#### GEO

-   [*Herramientas de análisis espacial en R*](https://martinmontane.github.io/AnalisisEspacialEnR/), Martín Montané.

#### SOFTWARE / PROGRAMACIÓN

-   [*What They Forgot to Teach You About R*](https://rstats.wtf/), Jennifer Bryan & Jim Hester.

-   [*Happy Git and GitHub for the useR*](https://happygitwithr.com/), Jennifer Bryan, STAT 545 TAs & Jim Hester.

-   [*A Handbook for Teaching and Learning with R and RStudio*](https://rstudio4edu.github.io/rstudio4edu-book/)*,* Desirée De Leon & Alison Hill.
